swagger: "2.0"
info:
  version: 0.1.0
  title: Vizier DB - Web API for Container Server
  description: API to to manipulate projects and to access project resources for project servers
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
schemes:
  - http
#host: cds-swg1.cims.nyu.edu
host: localhost:5005
basePath: /vizier-db/api/v1

paths:
    #
    # Overview
    #
    /:
        get:
            summary: Service description
            description: Essential information about the web service and relevant links
            operationId: serviceOverview
            tags:
                - service
            produces:
                - application/json
            responses:
                200:
                    description: Service descriptor
                    schema:
                        $ref: './schema.yaml#/ServiceDescriptor'
    #
    # Tasks
    #
    /tasks/execute:
        post:
            summary: Execute task
            description: Execute a task against a given project context
            operationId: executeTask
            tags:
                - task
            parameters:
                - name: module
                  in: body
                  required: true
                  description: Definition of module
                  schema:
                      $ref: './schema.yaml#/TaskStatement'
            produces:
                - application/json
            responses:
                200:
                    description: Operation result
                    schema:
                        $ref: './schema.yaml#/TaskRequestResult'
                400:
                    description: Invalid task statement
    /tasks/{taskId}/cancel:
        post:
            summary: Cancel workflow
            description: Cancel execution of all running or pending modules in the branch head
            operationId: cancelWorkflow
            tags:
                - task
            parameters:
                - name: taskId
                  in: path
                  required: true
                  description: The unique task identifier
                  type: string
            produces:
                - application/json
            responses:
                200:
                    description: Operation result
                    schema:
                        $ref: './schema.yaml#/TaskRequestResult'
                404:
                    description: Unknown task
    #
    # Datasets
    #
    /datasets:
        post:
            summary: Create dataset
            description: Create dataset from given schema and rows
            operationId: createDataset
            tags:
                - dataset
            parameters:
                - name: dataset
                  in: body
                  description: Dataset schema, rows, and optional annotations
                  required: true
                  schema:
                      $ref: './schema.yaml#/DatasetStatement'
            produces:
                - application/json
            responses:
                200:
                    description: Dataset handle
                    schema:
                        $ref: './schema.yaml#/DatasetDescriptor'
                400:
                    description: Invalid request
                404:
                    description: Unknown project
    /datasets/{datasetId}:
        get:
            summary: Get dataset
            description: Get columns and cell values for dataset
            operationId: getDataset
            tags:
                - dataset
            parameters:
                - name: datasetId
                  in: path
                  required: true
                  description: The unique dataset identifier
                  type: string
                - name: offset
                  in: query
                  required: false
                  description: Row offset for pagination
                  type: integer
                - name: limit
                  in: query
                  required: false
                  description: Row limit for pagination
                  type: integer
            produces:
                - application/json
            responses:
                200:
                    description: Dataset data
                    schema:
                        $ref: './schema.yaml#/DatasetHandle'
                404:
                    description: Unknown dataset
    /datasets/{datasetId}/annotations:
        get:
            summary: Get dataset annotations
            description: Get all annotations that are associated with dataset components
            operationId: getDatasetAnnotations
            tags:
                - dataset
            parameters:
                - name: datasetId
                  in: path
                  required: true
                  description: The unique dataset identifier
                  type: string
                - name: column
                  in: query
                  required: false
                  description: Unique column identifier
                  type: integer
                - name: row
                  in: query
                  required: false
                  description: Unique row identifier
                  type: integer
            produces:
                - application/json
            responses:
                200:
                    description: Dataset data
                    schema:
                        $ref: './schema.yaml#/DatasetAnnotations'
                404:
                    description: Unknown dataset
        post:
            summary: Update dataset annotations
            description: Update an annotations that is associated with a dataset component
            operationId: updateDatasetAnnotation
            tags:
                - dataset
            parameters:
                - name: datasetId
                  in: path
                  required: true
                  description: The unique dataset identifier
                  type: string
                - name: annotation
                  in: body
                  description: Update annotation statement
                  required: true
                  schema:
                      $ref: './schema.yaml#/UpdateAnnotationStatement'
            produces:
                - application/json
            responses:
                200:
                    description: Dataset data
                    schema:
                        $ref: './schema.yaml#/DatasetAnnotations'
                400:
                    description: Invalid request
                404:
                    description: Unknown dataset
    /datasets/{datasetsIdentifier}/csv:
        get:
            summary: Get CSV file
            description: Get dataset in CSV format
            operationId: downloadDataset
            tags:
                - dataset
            parameters:
                - name: datasetsIdentifier
                  in: path
                  required: true
                  description: The unique datasets identifier
                  type: string
            produces:
                - text/csv
            responses:
                200:
                    description: CSV file
                404:
                    description: Unknown datasets
    /datasets/{datasetId}/descriptor:
        get:
            summary: Get dataset descriptor
            description: Get short descriptor for a dataset
            operationId: getDatasetDescriptor
            tags:
                - dataset
            parameters:
                - name: datasetId
                  in: path
                  required: true
                  description: The unique dataset identifier
                  type: string
            produces:
                - application/json
            responses:
                200:
                    description: Dataset data
                    schema:
                        $ref: './schema.yaml#/DatasetDescriptor'
                404:
                    description: Unknown project or dataset
    #
    # Views
    #
    /branches/{branchId}/workflows/{workflowId}/modules/{moduleId}/views/{viewId}:
        get:
            summary: Get dataset view
            description: Access content of a dataset view for a given workflow module version
            operationId: getDatasetChartView
            tags:
                - chart
            parameters:
                - name: projectId
                  in: path
                  required: true
                  description: The unique project identifier
                  type: string
                - name: branchId
                  in: path
                  required: true
                  description: Unique identifier of the project branch
                  type: string
                - name: workflowId
                  in: path
                  required: true
                  description: Unique workflow identifier
                  type: string
                - name: moduleId
                  in: path
                  required: true
                  description: Identifier of module
                  type: string
                - name: viewId
                  in: path
                  required: true
                  description: Identifier of chart view
                  type: string
            produces:
                - application/json
            responses:
                200:
                    description: Dataset chart view content
                    schema:
                        $ref: './schema.yaml#/DatasetChartView'
                404:
                    description: Unknown project, branch, workflow, module, or view
    #
    # Files
    #
    /files:
        post:
            summary: Upload file
            description: Upload file from local disk
            operationId: uploadFile
            tags:
                - file
            parameters:
                - name: file
                  in: formData
                  required: true
                  description: File data
                  type: file
            consumes:
                - multipart/form-data
            produces:
                - application/json
            responses:
                201:
                    description: Upload successful
                    schema:
                        $ref: "./schema.yaml#/FileHandle"
                400:
                    description: Invalid file or request
                413:
                    description: Uploaded file size exceeds limit
    /files/{fileId}:
        get:
            summary: Download file
            description: Download file from file server
            operationId: downloadFile
            tags:
                - file
            parameters:
                - name: fileId
                  in: path
                  required: true
                  description: Unique file identifier
                  type: string
            produces:
                - text/csv
                - application/gzip
            responses:
                200:
                    description: File
                404:
                    description: Unknown file
