webservice:
    server_url: 'http://localhost'
    server_port: 5005
    server_local_port: 5005
    app_path: '/vizier-db-container/api/v1'
    name: 'Development Container Server API'
    defaults:
        max_file_size: 16777216
engine:
    identifier: 'DEV'
    properties:
        backend: 'MULTIPROCESS'
        filestore: './.vizierdb/fs/23885dc1'
        datastore: './.vizierdb/ds/23885dc1'
        packages:
            - declaration: './resources/packages/python.pckg.json'
              engine:
                  className: 'PyCellTaskProcessor'
                  moduleName: 'vizier.engine.packages.pycell.processor'
            - declaration: './resources/packages/plot.pckg.json'
              engine:
                  className: 'PlotProcessor'
                  moduleName: 'vizier.engine.packages.plot.processor'
            - declaration: './resources/packages/vizual.pckg.json'
              engine:
                  className: 'VizualTaskProcessor'
                  moduleName: 'vizier.engine.packages.vizual.processor'
                  properties:
                        api:
                            className: 'DefaultVizualApi'
                            moduleName: 'vizier.engine.packages.vizual.api.fs'
project_id: '23885dc1'
debug: True
logs:
    server: './.vizierdb/logs'
