language: python
python:
  - "3.8"
 
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
        key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823'
    packages:
      - openjdk-8-jdk
      - sbt
      
install:
  - pip3 install vizier-webapi
  - pip3 install -r requirements.txt
  - git clone https://github.com/UBOdin/mimir-api.git

branches:
  only:
  - master

script:
  - ./tools/test all

