api:
    server_url: 'http://localhost'
    server_port: 5000
    server_local_port: 5000
    app_path: '/vizier-db/api/v1'
    doc_url: 'http://cds-swg1.cims.nyu.edu/vizier-db/doc/api/v1'
envs:
    name: 'MIMIR'
    datastore:
        directory: '../.env/ds'
    workflows:
        directory: '../.env/wf'
viztrails:
    directory: '../.env/wf'
fileserver:
    directory: '../.env/fs'
    max_file_size: 16777216
name: 'Vizier Web API'
debug: True
logs: '../.env/logs'
