datastore:
    module: 'vizier.datastore.fs'
    class: 'FileSystemDatastore'
    properties:
        directory: './.vizierdb/datasets'
debug: True
filestore:
    module: 'vizier.filestore.fs'
    class: 'DefaultFilestore'
    properties:
        directory: './.vizierdb/files'
logs:
    server: './.vizierdb/logs'
packages:
    - './resources/packages/mimir.pckg.json'
    - './resources/packages/plot.pckg.json'
    - './resources/packages/python.pckg.json'
viztrails:
    module: 'vizier.viztrail.driver.objectstore.repository'
    class: 'OSViztrailRepository'
    properties:
        directory: './.vizierdb/viztrails'
webservice:
    server_url: 'http://localhost'
    server_port: 5000
    server_local_port: 5000
    app_path: '/vizier-db/api/v1'
    name: 'Vizier Web API'
    doc_url: 'http://cds-swg1.cims.nyu.edu/doc/vizier-db/'
    defaults:
        max_file_size: 16777216
