#!/bin/bash

DIR=$(dirname $0)/..
cd $DIR

if [ "$(which flake8)" ] ; then
  flake8 --config=.flake8 vizier || exit -1 
  echo "No Errors"
else
  echo "flake8 is not installed"
  echo
  echo "$> pip3 install flake8"
fi
